### ISSUE TITLE
'_URLFetchResult' object has no attribute 'status'

### ISSUE THREAD

**Issue by smittysmee** [recurly/recurly-client-python#114] opened 2015-06-09 16:00 UTC
I am experiencing an issue after making are request to recurly via the http_request method. 

The given response does not have the attribute 'status' when looking for a status code to validate against.

Rather, the attribute is 'status_code' and not 'status'  

Method:

                def reopen(self):
                        """Reopen a closed account."""
                        url = urljoin(self._url, '%s/reopen' % self.account_code)
                        response = self.http_request(url, 'PUT')

                        if response.status != 200:
                            self.raise_http_error(response)

To Reproduce:
Close an account in recurly and attempt to make a purchase with that recurly account. 
One must re-open the account to make this call

Environment:
Running under Google App Engine in Python v2.7

**Comment by bhelx** [comment] 2015-06-26 21:29
@smittysmee Thanks for reporting this issue. I'm trying to reproduce. Here is my code:

```python
account = recurly.Account.get('closeme')
transaction = recurly.Transaction(amount_in_cents=100, currency='USD', account=account)
transaction.save()
```

`closeme` is an account that is closed. It seems to be properly re-opening the account and adding the transaction (which I believe is the expected behavior). Could you maybe provide a specific script I can run in isolation to reproduce your problem?

**Comment by bhelx** [comment] 2015-09-11 01:26
@smittysmee any update? Can you also check the type of `response` ? Kind of sounds like you have the opposite problem of this:

http://stackoverflow.com/questions/11720090/httpresponse-instance-has-no-attribute-status-code-in-python-django

**Comment by bhelx** [comment] 2015-09-22 18:21
Closing for now. Please re-open if you still need help.

**Closed by bhelx** 2015-09-22 18:21 UTC
